version: '3'

services:
  express-api-compose:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      API_PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db

  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"